export const DEFAULT_PLANS = [
  {
    name: 'DSA & System Design Bootcamp',
    description: 'Intensive daily routine for DSA practice, system design learning, and project development',
    dayType: 'weekday',
    activities: [
      {
        name: 'Wake + Freshen + Quick Breakfast',
        startTime: '08:00',
        endTime: '08:20',
        category: 'meal',
        description: 'Protein + light carbs. No scrolling.',
      },
      {
        name: 'Deep Work Block 1 — DSA',
        startTime: '08:20',
        endTime: '10:40',
        category: 'work',
        description: '2 LC Mediums OR 1 Medium + 1 Hard attempt. Timed problems. No phone. Add notes to Notion.',
      },
      {
        name: 'Break',
        startTime: '10:40',
        endTime: '11:00',
        category: 'break',
        description: 'Walk. Water. Reset dopamine.',
      },
      {
        name: 'Deep Work Block 2 — Flagship Project',
        startTime: '11:00',
        endTime: '12:30',
        category: 'work',
        description: 'APIs, Smart contract logic, Access control, DB queries, Error handling, Testing. End with 1 Git commit.',
      },
      {
        name: 'Lunch',
        startTime: '12:30',
        endTime: '13:30',
        category: 'meal',
        description: 'Eat slow. No screens. Digest properly.',
      },
      {
        name: 'Deep Work Block 3 — System Design',
        startTime: '13:30',
        endTime: '15:00',
        category: 'work',
        description: 'Daily 1-topic deep dive: Caching, Load balancing, Indexing, Sharding, Event queues, Consistency models. Create 1 diagram, 1-page summary, 1 voice note.',
      },
      {
        name: 'Break',
        startTime: '15:00',
        endTime: '15:15',
        category: 'break',
        description: 'Quick mental reset',
      },
      {
        name: 'Mock Interviews / Job Applications',
        startTime: '15:15',
        endTime: '17:00',
        category: 'work',
        description: 'Mon/Wed/Fri: Mock Interviews. Tue/Thu: Job Applications. Apply to 5 positions, send recruiter DM.',
      },
      {
        name: 'Project Polish / Light Work',
        startTime: '17:00',
        endTime: '18:00',
        category: 'work',
        description: 'UI fixes, Documentation, README, Architecture diagram, CI/CD improvements, Demo recording.',
      },
      {
        name: 'Gymming',
        startTime: '18:00',
        endTime: '19:30',
        category: 'exercise',
        description: 'Perfect time: 80% work done, mental fatigue resets, evening energy rises, better sleep.',
      },
      {
        name: 'Dinner',
        startTime: '19:30',
        endTime: '20:30',
        category: 'meal',
        description: 'Eat enough to refuel but don\'t overeat. No screens.',
      },
      {
        name: 'Night Session — Light Intensity',
        startTime: '20:30',
        endTime: '21:20',
        category: 'work',
        description: 'DSA review, System design revision, Resume tweaks, LinkedIn networking, or Engineering content.',
      },
      {
        name: 'Daily Wrap-up',
        startTime: '21:20',
        endTime: '21:40',
        category: 'personal',
        description: 'Update Notion with DSA solved, Project hours, Commits, SD topic, Applications, Energy level, and blockers. Set next day\'s Top 3 Priorities.',
      },
      {
        name: 'Sleep',
        startTime: '23:00',
        endTime: '08:00',
        category: 'personal',
        description: '7-7.5 hours minimum sleep.',
      },
    ],
  },
  {
    name: 'DSA & System Design Bootcamp - Weekend',
    description: 'Weekend routine - Saturday high output, Sunday recovery + planning',
    dayType: 'weekend',
    activities: [
      {
        name: 'Project Deep Block',
        startTime: '08:30',
        endTime: '10:30',
        category: 'work',
        description: 'Saturday: High output focused work on flagship project.',
      },
      {
        name: 'Break',
        startTime: '10:30',
        endTime: '10:45',
        category: 'break',
        description: 'Quick reset',
      },
      {
        name: 'DSA Heavy / Contest',
        startTime: '10:45',
        endTime: '12:15',
        category: 'work',
        description: 'Saturday: DSA practice or coding contest preparation.',
      },
      {
        name: 'Lunch',
        startTime: '12:15',
        endTime: '13:15',
        category: 'meal',
        description: 'Eat slow. No screens.',
      },
      {
        name: 'System Design Deep Dive',
        startTime: '13:15',
        endTime: '15:30',
        category: 'work',
        description: 'Saturday: Extended system design session.',
      },
      {
        name: 'Documentation + Demo',
        startTime: '15:30',
        endTime: '17:00',
        category: 'work',
        description: 'Saturday: Project documentation and demo preparation.',
      },
      {
        name: 'Weekly Review + Planning',
        startTime: '09:30',
        endTime: '11:00',
        category: 'personal',
        description: 'Sunday: Review the week, plan next week.',
      },
      {
        name: 'Light DSA',
        startTime: '11:00',
        endTime: '12:00',
        category: 'work',
        description: 'Sunday: Relaxed DSA review.',
      },
      {
        name: 'Lunch',
        startTime: '12:00',
        endTime: '13:00',
        category: 'meal',
        description: 'Eat slow. No screens.',
      },
      {
        name: 'Gymming',
        startTime: '18:00',
        endTime: '19:30',
        category: 'exercise',
        description: 'Both Saturday and Sunday - before dinner.',
      },
    ],
  },
  {
    name: 'Balanced Learning Schedule',
    description: 'Flexible routine balancing work, learning, and self-care',
    dayType: 'weekday',
    activities: [
      {
        name: 'Morning Routine',
        startTime: '07:00',
        endTime: '08:00',
        category: 'personal',
        description: 'Exercise, breakfast, prepare for the day.',
      },
      {
        name: 'Deep Work Session 1',
        startTime: '08:00',
        endTime: '10:30',
        category: 'work',
        description: 'Focus on most important tasks.',
      },
      {
        name: 'Break',
        startTime: '10:30',
        endTime: '11:00',
        category: 'break',
        description: 'Rest and recharge.',
      },
      {
        name: 'Deep Work Session 2',
        startTime: '11:00',
        endTime: '12:30',
        category: 'work',
        description: 'Continue focused work.',
      },
      {
        name: 'Lunch',
        startTime: '12:30',
        endTime: '13:30',
        category: 'meal',
        description: 'Eat and rest.',
      },
      {
        name: 'Afternoon Session',
        startTime: '13:30',
        endTime: '17:00',
        category: 'work',
        description: 'Meetings, emails, collaborative work.',
      },
      {
        name: 'Evening Activity',
        startTime: '17:00',
        endTime: '18:30',
        category: 'exercise',
        description: 'Gym, walk, or hobby.',
      },
      {
        name: 'Dinner & Wind Down',
        startTime: '18:30',
        endTime: '21:00',
        category: 'personal',
        description: 'Dinner, personal time, relax.',
      },
    ],
  },
];
